
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."champions" (
    "id" smallint NOT NULL,
    "champion_name" character varying NOT NULL,
    "champion_id" smallint NOT NULL
);

ALTER TABLE "public"."champions" OWNER TO "postgres";

ALTER TABLE "public"."champions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."champion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."highlight_players" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "player_id" bigint NOT NULL,
    "highlight_id" integer NOT NULL,
    "player_highlight_type" character varying NOT NULL
);

ALTER TABLE "public"."highlight_players" OWNER TO "postgres";

ALTER TABLE "public"."highlight_players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."highlight_players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."highlight_tags" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "highlight_id" integer NOT NULL,
    "tag_id" smallint NOT NULL
);

ALTER TABLE "public"."highlight_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."highlight_tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."highlight_tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."highlight_tags_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."highlights" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "bunny_video_key" character varying NOT NULL,
    "start_timestamp" integer NOT NULL,
    "end_timestamp" integer NOT NULL,
    "match_id" character varying NOT NULL,
    "region" character varying NOT NULL
);

ALTER TABLE "public"."highlights" OWNER TO "postgres";

ALTER TABLE "public"."highlights" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."highlights_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."match_players" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "participant_id" smallint NOT NULL,
    "champion_id" smallint NOT NULL,
    "player_name" character varying NOT NULL,
    "team_id" smallint NOT NULL,
    "summoner_id" character varying NOT NULL,
    "match_id" bigint NOT NULL,
    "summoner_puuid" character varying NOT NULL,
    "tier" character varying NOT NULL,
    "rank" character varying NOT NULL,
    "league_points" character varying NOT NULL
);

ALTER TABLE "public"."match_players" OWNER TO "postgres";

ALTER TABLE "public"."match_players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."match_player_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."matches" (
    "id" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "game_id" bigint NOT NULL,
    "game_mode" integer NOT NULL,
    "creation_date" bigint NOT NULL,
    "region" character varying NOT NULL,
    "season" smallint NOT NULL
);

ALTER TABLE "public"."matches" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."platforms" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL
);

ALTER TABLE "public"."platforms" OWNER TO "postgres";

ALTER TABLE "public"."platforms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."platforms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."progamers" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "proteam_id" smallint NOT NULL
);

ALTER TABLE "public"."progamers" OWNER TO "postgres";

ALTER TABLE "public"."progamers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."progamers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."proteams" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "initial" character varying NOT NULL
);

ALTER TABLE "public"."proteams" OWNER TO "postgres";

ALTER TABLE "public"."proteams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proteams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."streamers" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "streamer_id" smallint NOT NULL,
    "name" character varying NOT NULL
);

ALTER TABLE "public"."streamers" OWNER TO "postgres";

ALTER TABLE "public"."streamers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."streamers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."summoners" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "puuid" character varying NOT NULL,
    "streamer_id" character varying,
    "progamer_id" character varying
);

ALTER TABLE "public"."summoners" OWNER TO "postgres";

ALTER TABLE ONLY "public"."champions"
    ADD CONSTRAINT "champion_champion_id_key" UNIQUE ("champion_id");

ALTER TABLE ONLY "public"."champions"
    ADD CONSTRAINT "champion_champion_name_key" UNIQUE ("champion_name");

ALTER TABLE ONLY "public"."champions"
    ADD CONSTRAINT "champion_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."highlight_players"
    ADD CONSTRAINT "highlight_players_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "highlight_tags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."highlight_tags"
    ADD CONSTRAINT "highlight_tags_pkey1" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."highlights"
    ADD CONSTRAINT "highlights_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."match_players"
    ADD CONSTRAINT "match_player_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."progamers"
    ADD CONSTRAINT "progamers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."proteams"
    ADD CONSTRAINT "proteams_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."streamers"
    ADD CONSTRAINT "streamers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."summoners"
    ADD CONSTRAINT "summoners_pkey" PRIMARY KEY ("puuid");

ALTER TABLE ONLY "public"."highlight_players"
    ADD CONSTRAINT "highlight_players_highlight_id_fkey" FOREIGN KEY ("highlight_id") REFERENCES "public"."highlights"("id");

ALTER TABLE ONLY "public"."highlight_players"
    ADD CONSTRAINT "highlight_players_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."match_players"("id");

ALTER TABLE ONLY "public"."highlight_tags"
    ADD CONSTRAINT "highlight_tags_highlight_id_fkey" FOREIGN KEY ("highlight_id") REFERENCES "public"."highlights"("id");

ALTER TABLE ONLY "public"."highlight_tags"
    ADD CONSTRAINT "highlight_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id");

ALTER TABLE ONLY "public"."highlights"
    ADD CONSTRAINT "highlights_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id");

ALTER TABLE ONLY "public"."match_players"
    ADD CONSTRAINT "match_players_champion_id_fkey" FOREIGN KEY ("champion_id") REFERENCES "public"."champions"("id");

ALTER TABLE ONLY "public"."match_players"
    ADD CONSTRAINT "match_players_summoner_puuid_fkey" FOREIGN KEY ("summoner_puuid") REFERENCES "public"."summoners"("puuid");

ALTER TABLE ONLY "public"."progamers"
    ADD CONSTRAINT "progamers_proteam_id_fkey" FOREIGN KEY ("proteam_id") REFERENCES "public"."proteams"("id");

ALTER TABLE "public"."champions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."highlight_players" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."highlight_tags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."highlights" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."match_players" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."matches" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."platforms" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."progamers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."proteams" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."streamers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."summoners" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."champions" TO "anon";
GRANT ALL ON TABLE "public"."champions" TO "authenticated";
GRANT ALL ON TABLE "public"."champions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."champion_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."champion_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."champion_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."highlight_players" TO "anon";
GRANT ALL ON TABLE "public"."highlight_players" TO "authenticated";
GRANT ALL ON TABLE "public"."highlight_players" TO "service_role";

GRANT ALL ON SEQUENCE "public"."highlight_players_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."highlight_players_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."highlight_players_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."highlight_tags" TO "anon";
GRANT ALL ON TABLE "public"."highlight_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."highlight_tags" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."highlight_tags_id_seq1" TO "service_role";

GRANT ALL ON TABLE "public"."highlights" TO "anon";
GRANT ALL ON TABLE "public"."highlights" TO "authenticated";
GRANT ALL ON TABLE "public"."highlights" TO "service_role";

GRANT ALL ON SEQUENCE "public"."highlights_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."highlights_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."highlights_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."match_players" TO "anon";
GRANT ALL ON TABLE "public"."match_players" TO "authenticated";
GRANT ALL ON TABLE "public"."match_players" TO "service_role";

GRANT ALL ON SEQUENCE "public"."match_player_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."match_player_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."match_player_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."matches" TO "anon";
GRANT ALL ON TABLE "public"."matches" TO "authenticated";
GRANT ALL ON TABLE "public"."matches" TO "service_role";

GRANT ALL ON TABLE "public"."platforms" TO "anon";
GRANT ALL ON TABLE "public"."platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."platforms" TO "service_role";

GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."progamers" TO "anon";
GRANT ALL ON TABLE "public"."progamers" TO "authenticated";
GRANT ALL ON TABLE "public"."progamers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."progamers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."progamers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."progamers_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."proteams" TO "anon";
GRANT ALL ON TABLE "public"."proteams" TO "authenticated";
GRANT ALL ON TABLE "public"."proteams" TO "service_role";

GRANT ALL ON SEQUENCE "public"."proteams_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proteams_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proteams_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."streamers" TO "anon";
GRANT ALL ON TABLE "public"."streamers" TO "authenticated";
GRANT ALL ON TABLE "public"."streamers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."streamers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."streamers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."streamers_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."summoners" TO "anon";
GRANT ALL ON TABLE "public"."summoners" TO "authenticated";
GRANT ALL ON TABLE "public"."summoners" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
